### PR TITLE
Add strikethrough support

### LINKED ISSUE #27: Strikethroughs
Github-Flavored Markdown adds strikethroughs. The parsing for this will be similar to how other inlines are parsed:

https://github.com/dillonkearns/elm-markdown/blob/master/src/Markdown/Inlines.elm#L23-L39

And the inline style record will need to keep track of whether we are in a strikethrough:

https://github.com/dillonkearns/elm-markdown/blob/master/src/Markdown/Block.elm#L68-L75

Here's the current behavior:

https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/%5Bextension%5D%20Strikethrough.md#example-491

Read more about it in [the Github-Flavored Markdown spec section on strikethrough](https://github.github.com/gfm/#strikethrough-extension-).

### PR DESCRIPTION
**Pull request by tadityar**
## What's In This PR
Support for strikethrough, closes #27. This PR also adds `~` to the list of punctuations.

Ran test for escaped stuff for good measure. You can compare the text below with the content in the spoiler.

**As formatted by GitHub**
`9999991`: `\~~~Hi~~` -> \~~~Hi~~ Hello, world!
`9999992`: `~~Hi~~\~` -> ~~Hi~~\~ Hello, world!
`9999993`: `~~Hi\~~` -> ~~Hi\~~ Hello, world!
`9999994`: `\~\~Hi\~\~` -> \~\~Hi\~\~ Hello, world!
`9999995`: `\~~Hi~\~` -> \~~Hi~\~ Hello, world! (oh hmm, just realised GitHub also accepts single tilde even though the spec says double)

<details>
<summary>test-cases testing escapes</summary>

```json
  {
    "section": "[extension] Strikethrough with escape 1",
    "html": "<p>~<del>Hi</del> Hello, world!</p>",
    "markdown": "\\~~~Hi~~ Hello, world!",
    "example": 9999991
  },
  {
    "section": "[extension] Strikethrough with escape 2",
    "html": "<p><del>Hi</del>~ Hello, world!</p>",
    "markdown": "~~Hi~~\\~ Hello, world!",
    "example": 9999992
  },
  {
    "section": "[extension] Strikethrough with escape 3",
    "html": "<p>~~Hi~~ Hello, world!</p>",
    "markdown": "~~Hi\\~~ Hello, world!",
    "example": 9999993
  },
  {
    "section": "[extension] Strikethrough with escape 4",
    "html": "<p>~~Hi~~ Hello, world!</p>",
    "markdown": "\\~\\~Hi\\~\\~ Hello, world!",
    "example": 9999994
  },
  {
    "section": "[extension] Strikethrough with escape 5",
    "html": "<p>~~Hi~~ Hello, world!</p>",
    "markdown": "\\~~Hi~\\~ Hello, world!",
    "example": 9999995
  }
```
</details>

<details>
<summary>passing-GFM.md diff</summary>

```diff
diff --git a/test-results/passing-GFM.md b/test-results/passing-GFM.md
index addadce..23f0573 100644
--- a/test-results/passing-GFM.md
+++ b/test-results/passing-GFM.md
@@ -9833,6 +9833,96 @@ Gives this correct output:
 <p>new paragraph~~.</p>
 
 
+## [extension] Strikethrough with escape 1
+
+### [Example 9999991](https://github.github.com/gfm/#example-9999991)
+
+This markdown:
+
+
+````````````markdown
+\~~~Hi~~ Hello, world!
+````````````
+
+Gives this correct output:
+
+
+````````````html
+<p>~<del>Hi</del> Hello, world!</p>
+````````````
+
+## [extension] Strikethrough with escape 2
+
+### [Example 9999992](https://github.github.com/gfm/#example-9999992)
+
+This markdown:
+
+
+````````````markdown
+~~Hi~~\~ Hello, world!
+````````````
+
+Gives this correct output:
+
+
+````````````html
+<p><del>Hi</del>~ Hello, world!</p>
+````````````
+
+## [extension] Strikethrough with escape 3
+
+### [Example 9999993](https://github.github.com/gfm/#example-9999993)
+
+This markdown:
+
+
+````````````markdown
+~~Hi\~~ Hello, world!
+````````````
+
+Gives this correct output:
+
+
+````````````html
+<p>~~Hi~~ Hello, world!</p>
+````````````
+
+## [extension] Strikethrough with escape 4
+
+### [Example 9999994](https://github.github.com/gfm/#example-9999994)
+
+This markdown:
+
+
+````````````markdown
+\~\~Hi\~\~ Hello, world!
+````````````
+
+Gives this correct output:
+
+
+````````````html
+<p>~~Hi~~ Hello, world!</p>
+````````````
+
+## [extension] Strikethrough with escape 5
+
+### [Example 9999995](https://github.github.com/gfm/#example-9999995)
+
+This markdown:
+
+
+````````````markdown
+\~~Hi~\~ Hello, world!
+````````````
+
+Gives this correct output:
+
+
+````````````html
+<p>~~Hi~~ Hello, world!</p>
+````````````
+
 ## [extension] Tables
 
 ### [Example 198](https://github.github.com/gfm/#example-198)

```
</details>

Feel free to squash on merge

### CODE REVIEW

**Review by dillonkearns — APPROVED** [review]

**Comment by dillonkearns** [comment]
It looks excellent, thank you so much!

**Comment by dillonkearns** [comment]
Those test cases that you outlined are really good. I think it would be worth adding those to the test suite for future reference and to prevent regressions.

Would you be up for adding those test cases in this module? https://github.com/dillonkearns/elm-markdown/blob/master/tests/Tests.elm

**Comment by tadityar** [comment]
Hi, yeah sure I’ll take a look at adding the test cases in. Will ping you again here or on Slack when I’m done 👍

**Comment by dillonkearns** [comment]
Sounds great, thank you!

**Comment by tadityar** [comment]
@dillonkearns added the tests!

**Comment by dillonkearns** [comment]
Looks great, thank you for adding those extra test cases!

**Comment by dillonkearns** [comment]
A new package version is live with this change: https://github.com/dillonkearns/elm-markdown/blob/master/CHANGELOG.md#600---2021-02-09.

Thank you again for the PR 🙏

**Pull request merged**
