### PR TITLE
Parse numbered lists

### PR DESCRIPTION
**Pull request by stephenreddek**
To address #5 

This is branched off of the work for PR #8 so the diff is not great yet. I think this is in the right direction. One notable change is the removal of the paragraph tag around the bodies of the list items. The type signature for the list renderer is harder to understand, but I believe it is more correct.

I see there is a failing test around a case where the list starts in the middle of a sentence but is on a new line (failing GM lists 274).

### CODE REVIEW

**Comment by stephenreddek** [comment]
I'm finding the case where there is a numeral inside of a paragraph (but still on a new line) to be very tricky. It seems like we need to know the context when starting to parse the ordered list so that we can fail if the numeral is not 1.

https://github.github.com/gfm/#example-284

**Comment by dillonkearns** [comment]
Hello @stephenreddek, this is looking great!

Do you think it's at a point where it's worth merging now, or is there more you wanted to address in this round? Either way is okay, just let me know if there's anything I can do to help.

Thank you!

**Comment by stephenreddek** [comment]
I should have updated the comment with exactly that information! I think it's at a good point now. I don't see any more additions from the spec that will be easy to add. If you see any failures that you think make sense to address before merging, I'd be happy to do them now. Otherwise, I'll come back to them later. I did figure out a decent way to handle the problem that I called out.

**Comment by stephenreddek** [comment]
The removal of the paragraph around the list items is a slight regression for some of the tests. I think it passes more than it fails, but it is certainly worth noting. The paragraph needs to be conditionally added depending on the contents as well as a few other factors.

**Comment by dillonkearns** [comment]
Hi @stephenreddek, sorry for the delay in getting this merged in. I'll push out a release now 👍

Thanks for your work on this, this is fantastic! 🎉

**Pull request merged**
