### PR TITLE
Parse lists with any of the valid markers

### PR DESCRIPTION
**Pull request by stephenreddek**
This is to handle #2 . I didn't track the opening marker in the RawBlock, but it is able to distinguish between lists of different markers. I hope this approach is acceptable!

### CODE REVIEW

**Comment by dillonkearns** [comment]
Hello @stephenreddek, thank you so much for opening the PR!

It looks like the list parsing is correct in the context of lists, but I'm seeing one tricky case that is coming up. Lines that start with an emphasis are being treated as lists 🤔

https://github.com/dillonkearns/elm-markdown/blob/237d063e75e074a0d4f603b46113b839be3c959d/test-results/failing/GFM/Emphasis%20and%20strong%20emphasis.md#example-350

I added a failing unit test to capture it. I'm not sure exactly what the right way to solve it is, it seems like it requires a little creative experimentation. Do you have any thoughts? Somehow interpreting the `*` as the beginning of an emphasis within a paragraph needs to take precedence over interpreting it as a List.

Do you have any interest in playing around with that more? I'd be happy to brainstorm with you, or take a shot at it myself.

Thanks again for the PR!

**Comment by stephenreddek** [comment]
Ah! That makes sense. I definitely skipped right over that situation. I'll spend some time poking around the rest of the codebase and think more about it. Making it a precedence operation makes lots of sense to me. My only concern with that would be with lots of backtracking - but backtracking may be required due to the standard.

**Comment by stephenreddek** [comment]
It looks like another distinguishing mark is whether or not there is a space after the asterisk.
`*this is emphasis*` is:
*this is emphasis*

while `* this is emphasis*` is:
* this is emphasis*

furthermore, `* this is *emphasis*` is:
* this is *emphasis*

So, it looks like we can simply require that space. That makes this simpler I think!

**Comment by stephenreddek** [comment]
I see that `* a *` is in the doc you linked (at 353), but it doesn't seem to work that way in GitHub. I'm testing these things with the write and the preview comment.

**Comment by dillonkearns** [comment]
@stephenreddek oh great point! Interesting that the spec has [that `* a *` example](https://github.github.com/gfm/#example-363) marked as emphasis. Let's ignore that for now. I'll do some more research on that, but especially since Github doesn't parse it that way either, that's definitely the way to go I think!

Thanks so much for putting all the thought and research into this!

**Comment by stephenreddek** [comment]
@dillonkearns Is there anything more I need to support for this particular feature? I can keep going through the spec with this PR or do that on future ones.

**Comment by dillonkearns** [comment]
Hi @stephenreddek, this looks absolutely fantastic! I think this is the perfect size for a PR, let's get this merged in and released and then we can do future specs in other PRs.

Thanks again for your work on this. It's so great to have your thoughtful contributions here! 🙏

**Comment by dillonkearns** [comment]
@all-contributors please add @stephenreddek for tests and code

**Comment by dillonkearns** [comment]
Published! https://github.com/dillonkearns/elm-markdown/blob/master/CHANGELOG.md#113---2019-11-13

**Pull request merged**
